"""Presentation (web demo) track helpers — aspect, paths, checkpoints, OBS."""

from __future__ import annotations

import json
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

PROJECT_ROOT = Path(__file__).resolve().parents[3]
TEMPLATE_ROOT = Path(
    os.getenv(
        "PRESENTATION_TEMPLATE_DIR",
        str(PROJECT_ROOT / "templates" / "web-presentation"),
    )
)
PRESENTATION_ROOT = Path(
    os.getenv(
        "PRESENTATION_DATA_DIR",
        str(PROJECT_ROOT / "data" / "presentations"),
    )
)

STAGE_SIZES: dict[str, tuple[int, int]] = {
    "16:9": (1920, 1080),
    "9:16": (1080, 1920),
}

CREATOR_UPLOAD_URL = "https://creator.douyin.com/creator-micro/content/upload"


def utc_now_iso() -> str:
    return (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )


def normalize_aspect(aspect: str | None) -> str:
    raw = (aspect or "16:9").strip()
    if raw in ("9:16", "9x16", "portrait", "vertical"):
        return "9:16"
    return "16:9"


def is_presentation(
    project: dict[str, Any] | None = None,
    meta: dict[str, Any] | None = None,
) -> bool:
    """True when project/meta marks the presentation track.

    Prefer wbmeta ``video_type`` over the DB column — InsForge check constraint
    only allows 图文/口播/剪辑, so presentation projects often store DB=口播.
    """
    meta_local = meta
    if meta_local is None and project:
        from cn_social_agent.video.pipeline import decode_script_bundle

        _plain, meta_local = decode_script_bundle(project.get("script") or "")
    candidates = []
    if meta_local:
        candidates.append(str(meta_local.get("video_type") or "").strip().lower())
    if project:
        candidates.append(str(project.get("video_type") or "").strip().lower())
    return any(v in ("presentation", "讲解演示", "web-presentation") for v in candidates)


def presentation_dir(project_id: str) -> Path:
    return PRESENTATION_ROOT / str(project_id)


def get_checkpoints(meta: dict[str, Any] | None) -> dict[str, Any]:
    raw = (meta or {}).get("checkpoints") or {}
    if not isinstance(raw, dict):
        return {}
    return raw


def checkpoint_confirmed(meta: dict[str, Any] | None, name: str) -> bool:
    block = get_checkpoints(meta).get(name) or {}
    if not isinstance(block, dict):
        return False
    return bool(block.get("confirmed"))


def require_checkpoint(meta: dict[str, Any] | None, name: str) -> Optional[str]:
    """Return error message if checkpoint missing, else None."""
    if checkpoint_confirmed(meta, name):
        return None
    label = "A1（口播/大纲/主题）" if name == "a1" else "B（网页验收/是否配音）"
    return f"需要先完成检查点 {label}"


def set_checkpoint(
    meta: dict[str, Any],
    name: str,
    *,
    confirmed: bool = True,
    **extra: Any,
) -> dict[str, Any]:
    cps = dict(get_checkpoints(meta))
    block = dict(cps.get(name) or {}) if isinstance(cps.get(name), dict) else {}
    block["confirmed"] = confirmed
    block["at"] = utc_now_iso()
    block.update({k: v for k, v in extra.items() if v is not None})
    cps[name] = block
    out = dict(meta)
    out["checkpoints"] = cps
    return out


def obs_checklist(
    *,
    aspect: str = "16:9",
    preview_url: str = "",
) -> dict[str, Any]:
    aspect_n = normalize_aspect(aspect)
    w, h = STAGE_SIZES[aspect_n]
    url = preview_url or ""
    if url and "auto=" not in url:
        sep = "&" if "?" in url else "?"
        url = f"{url}{sep}auto=1"
    return {
        "aspect": aspect_n,
        "width": w,
        "height": h,
        "preview_url": url,
        "steps": [
            f"OBS 画布设为 {w}×{h}（{aspect_n}）",
            "浏览器全屏打开预览链接（已带 ?auto=1）",
            "按空格一次解锁自动播放，之后按口播节奏自动推进",
            "OBS 开始录制 → 播完 → 停止",
            "回到工坊「导入成片」选择 OBS 输出的 mp4",
        ],
    }


def write_config_ts(dest: Path, *, aspect: str, theme: str, title: str) -> None:
    aspect_n = normalize_aspect(aspect)
    w, h = STAGE_SIZES[aspect_n]
    body = (
        "// Auto-generated by workbench scaffold — do not edit by hand\n"
        f"export const aspect = {json.dumps(aspect_n)} as const;\n"
        f"export const stageWidth = {w};\n"
        f"export const stageHeight = {h};\n"
        f"export const themeId = {json.dumps(theme or 'talent-map')};\n"
        f"export const title = {json.dumps(title or '讲解演示')};\n"
    )
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(body, encoding="utf-8")


def scaffold_project(
    project_id: str,
    *,
    aspect: str = "16:9",
    theme: str = "talent-map",
    title: str = "",
    template_root: Path | None = None,
) -> Path:
    """Copy template into data/presentations/{id} and write config.ts."""
    src = Path(template_root or TEMPLATE_ROOT)
    if not src.is_dir():
        raise FileNotFoundError(f"presentation template missing: {src}")
    dest = presentation_dir(project_id)
    if dest.exists():
        shutil.rmtree(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(
        src,
        dest,
        ignore=shutil.ignore_patterns(
            "node_modules", "dist", ".git", "*.log", ".DS_Store"
        ),
    )
    write_config_ts(
        dest / "src" / "config.ts",
        aspect=aspect,
        theme=theme,
        title=title,
    )
    return dest


def import_final_mp4(project_id: str, src_file: Path) -> Path:
    """Import recorded/OBS video as final.mp4 (webm/mkv converted via ffmpeg when possible)."""
    if not src_file.is_file():
        raise FileNotFoundError(str(src_file))
    suffix = src_file.suffix.lower()
    if suffix not in (".mp4", ".webm", ".mkv"):
        raise ValueError("only .mp4 / .webm supported")
    dest_dir = presentation_dir(project_id)
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / "final.mp4"
    if suffix == ".mp4":
        shutil.copy2(src_file, dest)
        return dest

    import subprocess

    try:
        proc = subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-i",
                str(src_file),
                "-c:v",
                "libx264",
                "-pix_fmt",
                "yuv420p",
                "-c:a",
                "aac",
                "-movflags",
                "+faststart",
                str(dest),
            ],
            capture_output=True,
            text=True,
            timeout=600,
            check=False,
        )
        if proc.returncode == 0 and dest.is_file() and dest.stat().st_size > 0:
            return dest
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        pass

    # Fallback: keep original container so preview/download still works
    dest_alt = dest_dir / f"final{suffix}"
    shutil.copy2(src_file, dest_alt)
    return dest_alt


def dist_dir(project_id: str) -> Path:
    return presentation_dir(project_id) / "dist"


def half_auto_douyin_payload(
    *,
    title: str,
    hashtags: list[str] | None = None,
    description: str = "",
) -> dict[str, Any]:
    tags = [t for t in (hashtags or []) if t]
    return {
        "platform": "douyin",
        "status": "skipped",
        "external_id": "",
        "url": CREATOR_UPLOAD_URL,
        "message": "未配置抖音开放平台凭证或未授权，已降级为半自动：复制文案后打开创作者中心上传",
        "clipboard": {
            "title": title or "",
            "hashtags": tags,
            "description": description or title or "",
        },
    }


def run_build(project_id: str, *, timeout: int = 300) -> dict[str, Any]:
    """Run npm install + vite build in presentation dir. Returns {ok, log, dist}.
    """
    import subprocess

    root = presentation_dir(project_id)
    if not (root / "package.json").is_file():
        return {"ok": False, "log": "package.json missing — scaffold first", "dist": ""}
    logs: list[str] = []
    for cmd in (
        ["npm", "install", "--no-fund", "--no-audit"],
        ["npm", "run", "build"],
    ):
        try:
            proc = subprocess.run(
                cmd,
                cwd=str(root),
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
            )
        except FileNotFoundError:
            return {"ok": False, "log": "npm/npx not found on PATH", "dist": ""}
        except subprocess.TimeoutExpired:
            return {"ok": False, "log": f"timeout running {' '.join(cmd)}", "dist": ""}
        logs.append(f"$ {' '.join(cmd)}\n{proc.stdout or ''}{proc.stderr or ''}")
        if proc.returncode != 0:
            return {"ok": False, "log": "\n".join(logs)[-4000:], "dist": ""}
    dist = root / "dist" / "index.html"
    return {
        "ok": dist.is_file(),
        "log": "\n".join(logs)[-2000:],
        "dist": str(root / "dist") if dist.is_file() else "",
    }


def apply_content_pack(project_id: str, pack_id: str = "ai-hiring-map") -> Path:
    """Copy pack chapters + narrations + CONTENT into an existing scaffold."""
    pack = TEMPLATE_ROOT / "packs" / pack_id
    if not pack.is_dir():
        raise FileNotFoundError(f"content pack missing: {pack}")
    dest = presentation_dir(project_id)
    if not (dest / "package.json").is_file():
        raise FileNotFoundError("scaffold first")
    chapters_src = pack / "chapters"
    chapters_dst = dest / "src" / "chapters"
    if chapters_dst.exists():
        shutil.rmtree(chapters_dst)
    shutil.copytree(chapters_src, chapters_dst)
    narr = pack / "narrations.ts"
    if narr.is_file():
        shutil.copy2(narr, dest / "src" / "narrations.ts")
    content = pack / "CONTENT.md"
    if content.is_file():
        shutil.copy2(content, dest / "CONTENT.md")
    pack_json = pack / "content.json"
    theme = "talent-map"
    title = ""
    if pack_json.is_file():
        raw = json.loads(pack_json.read_text(encoding="utf-8"))
        theme = str(raw.get("theme") or theme)
        title = str(raw.get("title") or "")
        save_content_json(project_id, raw)
    # Keep stage theme in sync with pack (avoid stale desk/black)
    cfg = dest / "src" / "config.ts"
    if cfg.is_file():
        # Preserve aspect from existing config if present
        aspect = "9:16"
        text = cfg.read_text(encoding="utf-8")
        for line in text.splitlines():
            if line.strip().startswith("export const aspect"):
                if "16:9" in line:
                    aspect = "16:9"
                break
        write_config_ts(cfg, aspect=aspect, theme=theme, title=title or "讲解演示")
    return dest


def content_json_path(project_id: str, *, built: bool = False) -> Path:
    root = presentation_dir(project_id)
    if built:
        return root / "dist" / "content.json"
    return root / "public" / "content.json"


def load_content_json(project_id: str) -> dict[str, Any]:
    """Prefer dist (live preview), then public."""
    for path in (content_json_path(project_id, built=True), content_json_path(project_id, built=False)):
        if path.is_file():
            try:
                return json.loads(path.read_text(encoding="utf-8"))
            except Exception:  # noqa: BLE001
                continue
    return {"title": "", "chapters": []}


def save_content_json(project_id: str, data: dict[str, Any]) -> Path:
    """Write editable slide content for live preview (dist) and future builds (public)."""
    root = presentation_dir(project_id)
    payload: dict[str, Any] = {
        "title": data.get("title") or "",
        "chapters": data.get("chapters") or [],
    }
    for key in ("theme", "outline", "full_script"):
        if data.get(key):
            payload[key] = data[key]
    text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    written: Path | None = None
    for rel in ("public/content.json", "dist/content.json"):
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written = path
    assert written is not None
    return written


def _write_narrations_json(project_id: str, payload: dict[str, Any]) -> None:
    root = presentation_dir(project_id)
    text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    for rel in ("public/narrations.json", "dist/narrations.json"):
        path = root / rel
        if rel.startswith("dist/") and not (root / "dist").is_dir():
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")


def estimate_narration_ms(text: str) -> int:
    """Rough speak time for Chinese narration (matches stage fallback pacing)."""
    chars = len((text or "").strip())
    if chars <= 0:
        return 2200
    return max(2200, chars * 120)


def slide_narration_text(slide: dict[str, Any]) -> str:
    if not isinstance(slide, dict):
        return ""
    return str(
        slide.get("narration") or slide.get("body") or slide.get("title") or ""
    ).strip()


def build_timeline_qc(
    *,
    total_slides: int,
    steps: dict[str, Any],
    timeline: list[dict[str, Any]],
) -> dict[str, Any]:
    """Content/audio alignment checks for presentation narrations."""
    issues: list[str] = []
    with_audio = sum(1 for s in steps.values() if isinstance(s, dict) and s.get("audio"))
    with_text = sum(1 for s in steps.values() if isinstance(s, dict) and str(s.get("text") or "").strip())
    missing_audio = [
        k
        for k, s in steps.items()
        if isinstance(s, dict) and str(s.get("text") or "").strip() and not s.get("audio")
    ]
    short_clips = [
        k
        for k, s in steps.items()
        if isinstance(s, dict)
        and int(s.get("duration_ms") or 0) > 0
        and int(s.get("duration_ms") or 0) < 1200
    ]
    if total_slides > 0 and with_text < max(1, total_slides // 2):
        issues.append(f"旁白覆盖不足：{with_text}/{total_slides} 步有口播文本")
    if missing_audio:
        issues.append(f"缺音频：{', '.join(missing_audio[:6])}")
    if short_clips:
        issues.append(f"过短片段（<1.2s）：{', '.join(short_clips[:6])}")
    if not timeline:
        issues.append("时间轴为空")
    checks = {
        "has_timeline": len(timeline) > 0,
        "coverage_ge_half": total_slides == 0
        or with_text >= max(1, total_slides // 2),
        "all_text_has_audio": len(missing_audio) == 0 and with_text > 0,
        "no_tiny_clips": len(short_clips) == 0,
    }
    return {
        "ok": all(checks.values()),
        "checks": checks,
        "issues": issues[:8],
        "stats": {
            "total_slides": total_slides,
            "with_text": with_text,
            "with_audio": with_audio,
            "steps": len(steps),
        },
    }


def _sync_durations_into_content(
    project_id: str,
    steps: dict[str, Any],
) -> None:
    """Write measured duration_ms back onto content.json slides."""
    content = load_content_json(project_id)
    chapters = content.get("chapters")
    if not isinstance(chapters, list):
        return
    changed = False
    for ci, ch in enumerate(chapters):
        if not isinstance(ch, dict):
            continue
        slides = ch.get("slides")
        if not isinstance(slides, list):
            continue
        for si, sl in enumerate(slides):
            if not isinstance(sl, dict):
                continue
            entry = steps.get(f"{ci}:{si}")
            if not isinstance(entry, dict):
                continue
            ms = int(entry.get("duration_ms") or 0)
            if ms <= 0:
                continue
            if int(sl.get("duration_ms") or 0) != ms:
                sl["duration_ms"] = ms
                changed = True
    if changed:
        save_content_json(project_id, content)


async def synthesize_presentation_narrations(
    project_id: str,
    *,
    voice: str = "zh-CN-XiaoxiaoNeural",
) -> dict[str, Any]:
    """TTS each slide → audio + narrations.json timeline for ?audio=1 / ?auto=1."""
    from cn_social_agent.video.pipeline import synthesize_tts

    root = presentation_dir(project_id)
    if not (root / "package.json").is_file():
        raise FileNotFoundError("scaffold first")
    content = load_content_json(project_id)
    chapters = content.get("chapters") or []
    if not isinstance(chapters, list) or not chapters:
        raise ValueError("暂无步骤内容，请先起草或应用内容包")

    public_audio = root / "public" / "audio"
    public_audio.mkdir(parents=True, exist_ok=True)
    dist_audio = root / "dist" / "audio"
    if (root / "dist").is_dir():
        dist_audio.mkdir(parents=True, exist_ok=True)

    steps: dict[str, Any] = {}
    timeline: list[dict[str, Any]] = []
    errors: list[str] = []
    total_slides = 0
    cursor_ms = 0

    for ci, ch in enumerate(chapters):
        if not isinstance(ch, dict):
            continue
        slides = ch.get("slides") or []
        if not isinstance(slides, list):
            continue
        for si, sl in enumerate(slides):
            if not isinstance(sl, dict):
                continue
            total_slides += 1
            text = slide_narration_text(sl)
            if not text:
                continue
            key = f"{ci}:{si}"
            fname = f"c{ci}_s{si}.mp3"
            out = public_audio / fname
            planned_ms = int(sl.get("duration_ms") or 0) or estimate_narration_ms(text)
            duration_ms = planned_ms
            audio_rel = ""
            try:
                dur_sec = await synthesize_tts(text, out, voice=voice)
                duration_ms = max(800, int(round(float(dur_sec) * 1000)))
                audio_rel = f"./audio/{fname}"
                if dist_audio.is_dir():
                    shutil.copy2(out, dist_audio / fname)
            except Exception as e:  # noqa: BLE001
                errors.append(f"{key} {type(e).__name__}: {e}")
                # Keep text+planned duration so auto mode can still pace
            entry = {
                "text": text[:280],
                "duration_ms": duration_ms,
                "start_ms": cursor_ms,
                "planned_ms": planned_ms,
            }
            if audio_rel:
                entry["audio"] = audio_rel
            steps[key] = entry
            timeline.append({"key": key, "ch": ci, "step": si, **entry})
            cursor_ms += duration_ms

    if not steps:
        raise ValueError(
            "未能合成任何旁白"
            + (f"：{errors[0]}" if errors else "（步骤正文为空？）")
        )

    qc = build_timeline_qc(
        total_slides=total_slides,
        steps=steps,
        timeline=timeline,
    )
    payload = {
        "version": 1,
        "voice": voice,
        "steps": steps,
        "timeline": timeline,
        "total_ms": cursor_ms,
        "qc": qc,
        # flat keys for older clients that treat root as Record<key, clip>
        **steps,
    }
    _write_narrations_json(project_id, payload)
    try:
        _sync_durations_into_content(project_id, steps)
    except Exception:  # noqa: BLE001
        pass

    return {
        "ok": bool(qc.get("ok")),
        "count": len(steps),
        "errors": errors[:8],
        "voice": voice,
        "total_ms": cursor_ms,
        "timeline": timeline,
        "qc": qc,
    }
